In [7]:
import pandas as pd
df1 = pd.read_csv(r"C:\Users\SHIVAM\Downloads\orders.csv\orders.csv")
df1.head(4)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2

In [9]:
df1['Ship Mode'].unique() # it shows what are the types of values present in a column

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

In [15]:
df = pd.read_csv(r'C:\Users\SHIVAM\Downloads\orders.csv\orders.csv', na_values=['Not Available', 'unknown'])

In [17]:
df['Ship Mode'].unique()
df.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent'],
      dtype='object')

In [21]:
df.rename(columns = {'City': 'city', 'Order Id': 'order_id'}) # renaming columns like this is tideous task

,order_id,Order Date,Ship Mode,Segment,Country,city,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [23]:
df.columns = df.columns.str.lower() # hence it should be renamed like this
df.columns = df.columns.str.replace(' ', '_')

In [27]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [29]:
df['discount'] = df['list_price']*df['discount_percent']*.01
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0

In [31]:
df['sale_price'] = df['list_price']-df['discount']
df['sale_price']

0       254.8
1       708.1
2         9.5
3       940.8
4        19.0
        ...
9989     28.8
9990     86.4
9991    254.8
9992     29.1
9993    232.8
Name: sale_price, Length: 9994, dtype: float64

In [33]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0

In [35]:
df['profit'] = df['sale_price'] - df['cost_price']
df.head(5)
df.dtypes

order_id              int64
order_date           object
ship_mode            object
segment              object
country              object
city                 object
state                object
postal_code           int64
region               object
category             object
sub_category         object
product_id           object
cost_price            int64
list_price            int64
quantity              int64
discount_percent      int64
discount            float64
sale_price          float64
profit              float64
dtype: object

In [37]:
df['order_date'] = pd.to_datetime(df['order_date'], format = '%Y-%m-%d') # initially order_date dtype was object we changed it to datetime

In [39]:
df.drop(columns = ['cost_price', 'discount_percent', 'list_price'], inplace = True)

In [41]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'quantity', 'discount', 'sale_price', 'profit'],
      dtype='object')

In [43]:
df.isnull().sum()

order_id        0
order_date      0
ship_mode       6
segment         0
country         0
city            0
state           0
postal_code     0
region          0
category        0
sub_category    0
product_id      0
quantity        0
discount        0
sale_price      0
profit          0
dtype: int64

In [45]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\shivam\anaconda3\lib\site-packages (9.2.0)

In [46]:
pip show mysql-connector-python # verification

Name: mysql-connector-pythonNote: you may need to restart the kernel to use updated packages.

Version: 9.2.0
Summary: A self-contained Python driver for communicating with MySQL servers, using an API that is compliant with the Python Database API Specification v2.0 (PEP 249).
Home-page:
Author: Oracle and/or its affiliates
Author-email:
License: GNU GPLv2 (with FOSS License Exception)
Location: C:\Users\SHIVAM\anaconda3\Lib\site-packages
Requires:
Required-by:

WARNING: Package(s) not found: #, verification

In [49]:
pip uninstall mysqlclient pymysql # to uninstall MySQL libraries (e.g., pymysql, mysqlclient, etc.), they may conflict

Note: you may need to restart the kernel to use updated packages.

ERROR: Invalid requirement: '#'

In [51]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\shivam\anaconda3\lib\site-packages (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [61]:
import pymysql

connection = pymysql.connect(
    host="localhost",
    user="root",
    password="shivam1234",
    database="shop",
    port=3306
)

print("Connected to MySQL Server!")

Connected to MySQL Server!

In [63]:
pip install sqlalchemy pandas pymysql

Requirement already satisfied: sqlalchemy in c:\users\shivam\anaconda3\lib\site-packages (2.0.30)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pandas in c:\users\shivam\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: pymysql in c:\users\shivam\anaconda3\lib\site-packages (1.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\shivam\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\shivam\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\shivam\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shivam\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shivam\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shivam\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\shivam\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [65]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\shivam\anaconda3\lib\site-packages (9.2.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import mysql.connector
import numpy as np

# Connect to MySQL
conn = mysql.connector.connect(
    host="127.0.0.1",
    port=3306,
    user="root",
    password="shivam1234",
    database="shop"
)
cursor = conn.cursor()

# Create table if not exists
cursor.execute("""
CREATE TABLE IF NOT EXISTS orders (
    order_id INT,
    order_date DATE,
    ship_mode VARCHAR(50),
    segment VARCHAR(50),
    country VARCHAR(100),
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    region VARCHAR(50),
    category VARCHAR(50),
    sub_category VARCHAR(50),
    product_id VARCHAR(100),
    quantity INT,
    discount FLOAT,
    sale_price FLOAT,
    profit FLOAT
)
""")

# Replace NaNs with None
df = df.replace({np.nan: None})

# Prepare data and insert
insert_query = """
INSERT INTO orders (
    order_id, order_date, ship_mode, segment, country, city, state, postal_code,
    region, category, sub_category, product_id, quantity, discount, sale_price, profit
) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""
data = [tuple(row) for row in df.itertuples(index=False)]
cursor.executemany(insert_query, data)

# Finalize
conn.commit()
cursor.close()
conn.close()

print("All records inserted successfully!")